#pragma once

#include <ntddk.h>

struct PacketDriverStats {
	ULONGLONG readRequests = 0;
	ULONGLONG readBytes = 0;
	ULONGLONG writeRequests = 0;
	ULONGLONG writeBytes = 0;
};

#define PACKETDRIVER_DEVICE_TYPE FILE_DEVICE_UNKNOWN
#define IOCTL_PACKETDRIVER_SET_MAX_READ CTL_CODE(PACKETDRIVER_DEVICE_TYPE, 0x800, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_PACKETDRIVER_SET_MAX_WRITE CTL_CODE(PACKETDRIVER_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_PACKETDRIVER_SET_FILLER CTL_CODE(PACKETDRIVER_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_PACKETDRIVER_GET_STATS CTL_CODE(PACKETDRIVER_DEVICE_TYPE, 0x803, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_PACKETDRIVER_GET_AND_RESET_STATS CTL_CODE(PACKETDRIVER_DEVICE_TYPE, 0x804, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_PACKETDRIVER_RESET_STATS CTL_CODE(PACKETDRIVER_DEVICE_TYPE, 0x805, METHOD_BUFFERED, FILE_WRITE_DATA)